config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # READ ALL THE TASK
  get '/tasks', to: 'tasks#index', as: :tasks

  # CREATE A TASK >> 2 REQUESTS
  # 1 DISPLAY THE FORM --> New
  get '/tasks/new', to: 'tasks#new'

  # 2 SAVE IN DB
  post '/tasks', to: 'tasks#create'

  # READ ONE TASK
  get '/tasks/:id', to: 'tasks#show', as: :task


  # UPDATE A TASK >> 2 REQUESTS
  # 1 DISPLAY THE FORM ALREADY FILLED IN - GET
  get '/tasks/:id/edit', to: 'tasks#edit', as: :task_edit
  # 2 POST PARAMS & UPDATE TO THE DB
  patch '/tasks/:id', to: 'tasks#update'

  # #DELETE A TASK
  delete '/tasks/:id', to: 'tasks#destroy'
  # delete '/restaurants/:id', to: "restaurants#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end


  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.label :completed %>
  <%= f.text_field :completed %>

  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>Here is the list of all tasks</h1>
<% @tasks.each do |task| %>
  <li>
   <%= link_to task.title, task_path(task) %>
   <%= link_to "destroy this task", task_path(task), method: :delete, data: {confirm: "Are your sure?"}  %></p>
  </li>
<% end %>

<%= link_to "Create a new task", tasks_new_path %>

app/views/tasks/new.html.erb
<h1>Create a new task?</h1>
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.label :completed %>
  <%= f.text_field :completed %>

  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1> <%= @task.title %> </h1>
<p> <%= @task.details %> </p>

<div>
  <input type="checkbox" id="task-complete" name="task-complete">
    <label for="task-complete">
      <% if @task.completed == nil %>
        <%= "Your task is not complete" %>
      <% else %>
        <%="Your task is complete!" %>
      <% end %>
    </label>
</div>

<ul>
  <li> <%= link_to "Back to task list", tasks_path %> </li>
  <li> <%= link_to "Edit this task", task_edit_path %> </li>
</ul>